services:
  backend:
    build: ../goldangtime
    image: goldengtime-docker/backend:latest
    ports:
      - "8080:8080"
    environment:
       - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
       - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
       - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
       - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - goldengtime-network

networks:
  goldengtime-network:
    driver: bridge
